### ISSUE TITLE
Bug: Ordering by 'Last Response' orders dates alphabetically

### ISSUE THREAD

**Issue by saulens22** [wh1te909/tacticalrmm#136]
![image](https://user-images.githubusercontent.com/9000854/95580531-29c6a100-0a40-11eb-916b-4a0fe2d3e6b2.png)

**Comment by wh1te909** [comment]
haha yea it's cuz am just using quasar's default sort function which sorts alphabetically and those dates are being sent as strings from the django rest api so it's not aware that it's a datetime. I'll need to implement a custom sort to parse it as a datetime.

**Comment by wh1te909** [comment]
fixed in https://github.com/wh1te909/tacticalrmm/pull/139 by @sadnub 
still have more work to do in other areas wherever there is a date but for now the agent table is fixed

**Comment by saulens22** [comment]
Issue persists, should be reopened.

![image](https://user-images.githubusercontent.com/9000854/103506611-c7761480-4e65-11eb-871a-d55e54de1ebb.png)

**Comment by dinger1986** [comment]
Looks to be resolved now, can I close this @saulens22 ?

**Comment by saulens22** [comment]
Yes, it works now
