### ISSUE TITLE
x509 certificate signed by unknown authority - Installing Agent Windows 10

### ISSUE THREAD

**Issue by al3xOA** [wh1te909/tacticalrmm#851]
Successfully installed tacticalrmm. When test installing an agent, during install I get the error described in the title. I've been poking and prodding around but my guess is the ssl cert correct? I'm using cloudflare as my dns but proxy is turned off on the api.x.com domain.

Would it be fair to see this is an ssl cert issue and to use the cloudflare ca cert to resolve the issue?

**Comment by dinger1986** [comment]
Maybe I suggest first of all that you redact your domain asap.

However I have checked and your rmm & mesh urls are working fine but your api one is showing a certificate error.

Are you using docker or standard install?

**Comment by al3xOA** [comment]
> 
I'm using a traditional install on esxi, fresh ubuntu lts. I'm thinking of possibly pointing the default lets encrypt certs to the cloudflare wildcard certs provided by cloudflare. I plan on uploading them to a certs folder as recommended by one of the torubleshooting pages on rmm to see if that's the issue.

Attached is the NAT service status error i'm seeing:
Dec 10 17:54:00 rmm nats-server[5521]: [5521] 2021/12/10 17:54:00.526011 [ERR] "redacted but personal ip":62762 - cid:5 - TLS handshake error: EOF

**Comment by dinger1986** [comment]
Yes put them on the machine and that should solve the issue, theres a guide for using your own certs

**Comment by dinger1986** [comment]
can we close this now?

**Comment by al3xOA** [comment]
> 

actually, after setting up the custom certs location and moving the cloudflare public and pirvate keys to the custom locations I still get the error. One final thing I was thinking is the original letsencrypt fullchain.pem has 3 certificates embedded as it should. My /certs/x.domain.com/fullchain.pem has the public key only. Could this be an issue?

**Comment by dinger1986** [comment]
No idea as don't use cloudflare for certs myself.

Suggested you discuss on #unsupported on our discord channel.

Closing on here as unsupported config
